const SUPABASE_URL="https://penntuaofjveawocdvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="PASTE_YOUR_EXISTING_SUPABASE_PUBLISHABLE_KEY_HERE";
const API_URL="https://reply-ai-api.xjillah.workers.dev";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let signup=false,currentUser=null,category="General",history=[],usage={count:0,limit:20,remaining:20,plan:"free"};
const $=id=>document.getElementById(id);
function authMsg(t){$("authMessage").textContent=t} function msg(t){$("status").textContent=t}
function mode(v){signup=v;$("loginTab").classList.toggle("active",!v);$("signupTab").classList.toggle("active",v);$("authTitle").textContent=v?"Create your account":"Welcome back";$("authSubtitle").textContent=v?"Create an account with email and password.":"Login with your email and password.";$("authBtn").textContent=v?"Create account":"Login";authMsg("")}
async function auth(){const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return authMsg("Enter email and password.");if(password.length<6)return authMsg("Password must be at least 6 characters.");$("authBtn").disabled=true;try{if(signup){const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:"https://jillah01.github.io/ai-whatsapp-reply/app.html"}});if(error)throw error;if(data.session)await showApp(data.user);else authMsg("Account created. Check your email to confirm, then log in.")}else{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;await showApp(data.user)}}catch(e){authMsg(e.message)}finally{$("authBtn").disabled=false}}
async function forgot(){const email=$("email").value.trim();if(!email)return authMsg("Enter your email first.");const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:"https://jillah01.github.io/ai-whatsapp-reply/app.html"});authMsg(error?"Error: "+error.message:"Password reset email sent.")}
async function showApp(user){currentUser=user;$("authCard").classList.add("hidden");$("appSection").classList.remove("hidden");$("userEmail").textContent=user.email||"Account";await loadData();await refreshUsage()}
function hideApp(){currentUser=null;$("authCard").classList.remove("hidden");$("appSection").classList.add("hidden");history=[];renderHistory()}
async function loadData(){const {data:p}=await sb.from("profiles").select("*").eq("id",currentUser.id).maybeSingle();if(p){$("businessName").value=p.business_name||"";$("businessType").value=p.business_type||"";$("language").value=p.language||"Hinglish";$("tone").value=p.tone||"Friendly";$("style").value=p.business_style||"";$("replyLanguage").value=p.language||"Hinglish";$("replyTone").value=p.tone||"Friendly"}const {data:r}=await sb.from("reply_history").select("*").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(10);history=r||[];renderHistory()}
async function refreshUsage(){try{const s=(await sb.auth.getSession()).data.session;if(!s)return;const r=await fetch(API_URL+"/usage",{headers:{Authorization:"Bearer "+s.access_token}});const d=await r.json();if(!r.ok)throw Error(d.error||"Usage lookup failed");usage={count:Number(d.count||0),limit:Number(d.limit||20),remaining:Number(d.remaining||0),plan:d.plan||"free"};$("usageCount").textContent=`${usage.count}/${usage.limit}`;$("usageLabel").textContent=usage.plan==="pro"?"Pro replies this month":"free replies this month"}catch(e){$("usageCount").textContent="—"}}
async function saveProfile(){const {error}=await sb.from("profiles").upsert({id:currentUser.id,business_name:$("businessName").value.trim(),business_type:$("businessType").value.trim(),language:$("language").value,tone:$("tone").value,business_style:$("style").value.trim(),updated_at:new Date().toISOString()});$("profileMessage").textContent=error?"Save failed: "+error.message:"Profile saved."}
async function ai(action="generate"){const s=(await sb.auth.getSession()).data.session;if(!s)throw Error("Please log in again.");const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+s.access_token},body:JSON.stringify({message:$("message").value.trim(),language:$("replyLanguage").value,tone:$("replyTone").value,category,businessName:$("businessName").value.trim(),businessType:$("businessType").value.trim(),businessStyle:$("style").value.trim(),action,existingReply:$("result").value.trim()})});const d=await r.json().catch(()=>({}));if(r.status===429){if(d.usage){usage=d.usage;$("usageCount").textContent=`${usage.count}/${usage.limit}`;$("usageLabel").textContent=usage.plan==="pro"?"Pro replies this month":"free replies this month"}throw Error(d.message||d.error||"Limit reached.")}if(r.status===401)throw Error("Please log in again.");if(!r.ok)throw Error(d.error||"Request failed.");if(!d.reply)throw Error("No reply returned.");if(d.usage){usage=d.usage;$("usageCount").textContent=`${usage.count}/${usage.limit}`;$("usageLabel").textContent=usage.plan==="pro"?"Pro replies this month":"free replies this month"}return d.reply}
async function generate(){if(!$("message").value.trim())return msg("Enter the customer's message.");if(usage.remaining<=0)return msg("You've reached the monthly limit.");$("generateBtn").disabled=true;$("generateBtn").textContent="Generating...";try{const reply=await ai();$("result").value=reply;$("resultSection").classList.remove("hidden");await saveReply($("message").value.trim(),reply);update();msg("Reply generated.")}catch(e){msg("Error: "+e.message)}finally{$("generateBtn").disabled=false;$("generateBtn").textContent="Generate Reply"}}
async function saveReply(message,reply){const {data,error}=await sb.from("reply_history").insert({user_id:currentUser.id,customer_message:message,reply,category,language:$("replyLanguage").value,tone:$("replyTone").value}).select().single();if(!error&&data){history.unshift(data);history=history.slice(0,10);renderHistory()}}
async function rewrite(action,b){if(!$("result").value.trim()||usage.remaining<=0)return;const old=b.textContent;b.disabled=true;b.textContent="Working...";try{$("result").value=await ai(action);await saveReply($("message").value.trim(),$("result").value);update();msg("Updated reply saved.")}catch(e){msg("Error: "+e.message)}finally{b.disabled=false;b.textContent=old}}
function update(){$("inputCount").textContent=$("message").value.length+"/1000";$("charCount").textContent=$("result").value.length+" characters"}
function renderHistory(){$("history").innerHTML=history.length?history.map((x,i)=>`<article class="history-item"><div class="history-top"><span class="tag">${esc(x.category||"General")}</span><span class="date">${esc(new Date(x.created_at).toLocaleString())}</span></div><p class="history-msg">${esc(x.customer_message||"")}</p><p class="history-reply">${esc(x.reply||"")}</p><div class="history-buttons"><button data-use="${i}">Use reply</button><button data-copy="${i}">Copy</button></div></article>`).join(""):'<div class="empty">No replies saved yet.</div>'}
function esc(t){return String(t).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
document.querySelectorAll(".category").forEach(b=>b.onclick=()=>{document.querySelectorAll(".category").forEach(x=>x.classList.remove("active"));b.classList.add("active");category=b.dataset.category});
$("loginTab").onclick=()=>mode(false);$("signupTab").onclick=()=>mode(true);$("authBtn").onclick=auth;$("forgotBtn").onclick=forgot;$("logoutBtn").onclick=async()=>{await sb.auth.signOut();hideApp()};$("saveProfileBtn").onclick=saveProfile;$("generateBtn").onclick=generate;$("message").oninput=update;$("language").onchange=()=>$("replyLanguage").value=$("language").value;$("tone").onchange=()=>$("replyTone").value=$("tone").value;$("copyBtn").onclick=async()=>{await navigator.clipboard.writeText($("result").value);$("copyBtn").textContent="✓ Copied";setTimeout(()=>$("copyBtn").textContent="📋 Copy",1000)};$("whatsappBtn").onclick=()=>window.open("https://wa.me/?text="+encodeURIComponent($("result").value),"_blank");$("shorterBtn").onclick=()=>rewrite("shorter",$("shorterBtn"));$("politeBtn").onclick=()=>rewrite("politer",$("politeBtn"));$("professionalBtn").onclick=()=>rewrite("professional",$("professionalBtn"));$("clearHistoryBtn").onclick=async()=>{const {error}=await sb.from("reply_history").delete().eq("user_id",currentUser.id);if(!error){history=[];renderHistory();msg("History cleared.")}};$("history").onclick=async e=>{const u=e.target.closest("[data-use]"),c=e.target.closest("[data-copy]");if(u){const x=history[+u.dataset.use];$("message").value=x.customer_message;$("result").value=x.reply;category=x.category||"General";document.querySelectorAll(".category").forEach(b=>b.classList.toggle("active",b.dataset.category===category));$("resultSection").classList.remove("hidden");update()}if(c){const x=history[+c.dataset.copy];await navigator.clipboard.writeText(x.reply);c.textContent="Copied"}};(async()=>{const {data}=await sb.auth.getSession();if(data.session)await showApp(data.session.user);else hideApp()})();
